/**
 * 贵州白酒品项库（56 支）。
 * 来源：团队《贵州白酒完整数据库》，栏位含香型、典型酒精度、工艺与风味描述。
 * 用途：让外贸专员直接选「你家要出的是哪一支」，而不是凭空填参数——
 * 选完之后香型、度数、风味描述会一起带进落地价测算与卖点弹药。
 */
import type { AromaId } from './aroma'

export type Baijiu = {
  id: string
  name: string
  en: string | null
  company: string | null
  origin: string | null
  zone: string | null
  aromaLabel: string | null
  aroma: AromaId | 'other'
  /** 典型酒精度 */
  abv: number
  /** 该品牌已有的度数版本（含低度版） */
  abvAll: number[]
  craft: string | null
  nose: string | null
  palate: string | null
  products: string | null
  honors: string | null
  status: string | null
  trust: string | null
}

export const BAIJIU: Baijiu[] = [
  {"id": "gz-01", "name": "茅台酒", "en": "Moutai / Maotai", "company": "贵州茅台酒股份有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区（茅台酒15.03km²核心区）", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 43, 38], "craft": "坤沙固态发酵：两次投料、九次蒸煮、八次发酵、七次取酒（12987），生产周期一年，基酒贮存三年以上，勾兑后再贮存一年，全程近五年", "nose": "酱香突出、香气优雅细腻、焦香与花果香层次分明", "palate": "醇厚丰满、酸度高、入口柔绵不烧喉", "products": "飞天茅台、五星茅台、茅台年份酒（15/30/50/80年）、珍品茅台", "honors": "1963贵州老八大名酒；1986贵州48优金樽奖；历届中国名酒；国家地理标志产品", "status": "在产（国内白酒龙头）", "trust": "已查证"},
  {"id": "gz-02", "name": "茅台王子酒", "en": "Maotai Wangzi", "company": "贵州茅台酒股份有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "与茅台酒同源之坤沙12987工艺，基酒等级与贮存年限低于飞天茅台", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "茅台王子酒（金王子/珍品/生肖）", "honors": "2011贵州十大名酒", "status": "在产（茅台系列酒主力）", "trust": "已查证"},
  {"id": "gz-03", "name": "茅台迎宾酒", "en": "Maotai Yingbin", "company": "贵州茅台酒股份有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙／碎沙结合之酱香工艺", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇和柔顺、酒体较轻盈", "products": "迎宾酒（紫/金/王）", "honors": "茅台系列酒", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-04", "name": "贵州大曲", "en": "Guizhou Daqu", "company": "贵州茅台酒股份有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 50], "craft": "酱香固态发酵（现行产品为酱香型；历史上的贵阳大曲/贵州大曲曾为浓香型，二者需区分）", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "贵州大曲（15年/30年、金酱/柔雅）", "honors": "1979贵州新八大名酒（贵阳大曲）", "status": "在产", "trust": "已查证"},
  {"id": "gz-05", "name": "汉酱酒", "en": "Hanjiang", "company": "贵州茅台酒股份有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 51, "abvAll": [51], "craft": "酱香12987工艺，以51度中度酱香为特色", "nose": "酱香突出、略带蜜甜与焦香", "palate": "酒体较柔和、入口绵顺", "products": "汉酱（匠心营造/135）", "honors": "茅台酱香系列酒", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-06", "name": "仁酒", "en": "Renjiu", "company": "贵州茅台酒股份有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "酱香12987工艺", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "茅台仁酒", "honors": "茅台酱香系列酒", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-07", "name": "赖茅", "en": "Laimao", "company": "贵州茅台酒厂（集团）赖茅酒业有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "酱香坤沙固态发酵", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "赖茅传承蓝/端曲/珍藏", "honors": "茅台三大烧房之一（恒兴烧房）源流", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-08", "name": "华茅", "en": "Huamao", "company": "贵州茅台酒厂（集团）华茅酒业有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "酱香坤沙固态发酵", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "华茅1862、华茅酒", "honors": "茅台三大烧房之一（成义烧房）源流", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-09", "name": "王茅", "en": "Wangmao", "company": "贵州茅台酒厂（集团）保健酒业／王茅品牌", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "酱香坤沙固态发酵", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "王茅酒、王茅使者", "honors": "茅台三大烧房之一（荣和烧房）源流", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-10", "name": "习酒", "en": "Xijiu", "company": "贵州习酒股份有限公司（原属茅台集团，现独立运营）", "origin": "遵义市习水县习酒镇", "zone": "赤水河中游（习水产区集聚区68.4km²）", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 52, 45], "craft": "赤水河谷传统固态法：两次投料、九次蒸煮、八次发酵、七次取酒，生产周期一年，长期陶坛贮存", "nose": "酱香突出、香气细腻纯正", "palate": "醇厚丰满、绵柔协调", "products": "君品习酒、窖藏1988、金质/银质习酒", "honors": "1986贵州48优金樽奖；2011贵州十大名酒", "status": "在产（贵州第二大酒企）", "trust": "已查证"},
  {"id": "gz-11", "name": "习水大曲", "en": "Xishui Daqu", "company": "贵州习酒股份有限公司", "origin": "遵义市习水县", "zone": "赤水河中游", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52, 38], "craft": "浓香型固态续糟发酵、泥窖老窖", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "习水大曲（经典/老标）", "honors": "1979贵州新八大名酒；1986贵州48优金樽奖", "status": "在产（习酒浓香产品线）", "trust": "史料/评选记载"},
  {"id": "gz-12", "name": "珍酒", "en": "Zhenjiu", "company": "珍酒李渡集团／贵州珍酒酿酒有限公司", "origin": "遵义市汇川区（原遵义酒精厂址）", "zone": "遵义汇川特色产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "茅台工艺异地移植：坤沙12987、长期贮存勾调，被称为「易地茅台」", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "珍十五、珍三十、珍酒真藏", "honors": "1986贵州48优银樽奖；国家科技进步奖（易地茅台试验）", "status": "在产（港股上市集团核心品牌）", "trust": "已查证"},
  {"id": "gz-13", "name": "国台酒", "en": "Guotai", "company": "贵州国台酒业集团（天士力控股）", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区（茅台镇传统优势区）", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙12987，以智能酿造与数字化品控著称，基酒贮存5年以上", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "国台国标酒、国台十五年、龙酒", "honors": "2011贵州十大名酒；被称茅台镇第二大酿酒企业", "status": "在产", "trust": "已查证"},
  {"id": "gz-14", "name": "钓鱼台酒", "en": "Diaoyutai", "company": "贵州钓鱼台国宾酒业有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "传承古典酱香工艺、天然酿制，坤沙12987", "nose": "酱香幽雅、细腻协调", "palate": "醇和优雅、酒体绵柔", "products": "钓鱼台国宾酒、珍品／年份系列", "honors": "国宾馆用酒品牌授权", "status": "在产", "trust": "已查证"},
  {"id": "gz-15", "name": "金沙回沙酒", "en": "Jinsha Huisha", "company": "贵州金沙窖酒酒业有限公司", "origin": "毕节市金沙县", "zone": "赤水河上游（金沙特色产区）", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "与茅台同源之回沙工艺：两次投料、九次蒸煮、八次发酵、七次取酒", "nose": "酱香突出、伴焦香与花果香，优雅细腻", "palate": "醇厚协调、层次分明、口感均衡", "products": "金沙摘要、金沙回沙钻石五星／年份、金沙六星", "honors": "1963贵州老八大名酒（金沙窖酒）；1986贵州48优银樽奖；2011贵州十大名酒", "status": "在产", "trust": "已查证"},
  {"id": "gz-16", "name": "怀庄酒", "en": "Huaizhuang", "company": "贵州怀庄酒业（集团）有限责任公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙酱香12987固态发酵", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "怀庄之醉、怀庄1983", "honors": "茅台镇早期民营酒企之一", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-17", "name": "夜郎古酒", "en": "Yelanggu", "company": "贵州夜郎古酒业股份有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙酱香12987", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "夜郎古酒（藏品/尊品）", "honors": "以夜郎文化为品牌核心", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-18", "name": "小糊涂仙", "en": "Xiaohutuxian", "company": "贵州小糊涂仙酒业（云峰酒业）", "origin": "遵义市仁怀市茅台镇（另有习水土城及四川合江基地）", "zone": "赤水河流域", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [53, 52], "craft": "传统浓香固态发酵结合现代生物技术；酱香产品采赤水河酱香工艺", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "小糊涂仙普仙、小糊涂神、糊涂尊", "honors": "1990年代广东市场现象级品牌", "status": "在产", "trust": "已查证"},
  {"id": "gz-19", "name": "百年糊涂", "en": "Bainian Hutu", "company": "贵州仁怀茅台镇糊涂酒业有限公司（佛山吉利贸易运营）", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "百年糊涂精品、海藏珍品", "honors": "2011贵州十大名酒", "status": "在产", "trust": "已查证"},
  {"id": "gz-20", "name": "酒中酒霸", "en": "Jiuzhongjiuba", "company": "贵州酒中酒（集团）有限责任公司", "origin": "遵义市仁怀市", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 52], "craft": "集团同时具备酱香与浓香两条产线；酱香采坤沙工艺", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "酒中酒霸、本强系列", "honors": "2011贵州十大名酒", "status": "在产", "trust": "已查证"},
  {"id": "gz-21", "name": "无忧酒", "en": "Wuyou", "company": "贵州无忧酒业有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙酱香12987", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "无忧酒系列", "honors": "茅台镇区域品牌", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-22", "name": "金酱酒", "en": "Jinjiang", "company": "贵州金酱酒业有限公司", "origin": "遵义市仁怀市茅台镇", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙酱香12987", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "金酱酒（年份/传承）", "honors": "茅台镇区域品牌", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-23", "name": "国威酒", "en": "Guowei", "company": "贵州国威酒业（集团）有限公司", "origin": "遵义市仁怀市", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙酱香固态发酵", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "国威酒系列", "honors": "仁怀本地老牌酒企", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-24", "name": "怀酒", "en": "Huaijiu", "company": "仁怀怀酒厂（现属茅台集团体系）", "origin": "遵义市仁怀市", "zone": "赤水河核心产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "酱香固态发酵", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "怀酒", "honors": "1986贵州48优金樽奖", "status": "在产（品牌经多次易手）", "trust": "史料/评选记载"},
  {"id": "gz-25", "name": "播窖1935", "en": "Bojiao 1935", "company": "贵州播窖酒业", "origin": "遵义市播州区", "zone": "遵义播州特色产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "酱香固态发酵", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "播窖1935", "honors": "区域新品牌", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-26", "name": "董酒", "en": "Dongjiu", "company": "贵州董酒股份有限公司", "origin": "遵义市汇川区董公寺镇", "zone": "遵义董公寺（独立产区）", "aromaLabel": "董香型（药香型）", "aroma": "herbal", "abv": 54, "abvAll": [59, 54, 38], "craft": "串香＋双醅法：大窖（泥窖）产香醅、小窖（土窖）产酒醅，两醅串蒸；「百草入曲、两小两大、双醅串蒸」", "nose": "药香（百草香）舒适优雅，酯香、醇香、药香协调", "palate": "醇和浓郁、饮后甘爽、微带酸涩而回甜", "products": "国密董酒、佰草香、密藏、红标／白标董酒", "honors": "中国老八大名酒；1963贵州老八大名酒；1986贵州48优金樽奖；2011贵州十大名酒；工艺列入国家", "status": "在产", "trust": "已查证"},
  {"id": "gz-27", "name": "鸭溪窖酒", "en": "Yaxi Jiao", "company": "贵州鸭溪窖酒有限公司", "origin": "遵义市播州区鸭溪镇", "zone": "黔北浓香带", "aromaLabel": "浓香型（带兼香特征：入口浓香、回味酱香）", "aroma": "sauce", "abv": 53, "abvAll": [55], "craft": "泥窖固态续糟发酵，浓香工艺但成品带酱香尾韵，称「黔派浓香」", "nose": "芳香浓郁、入口浓香而回味带酱", "palate": "醇甜爽口、甜而不暴", "products": "鸭溪窖酒（经典/珍品）", "honors": "1963贵州老八大名酒；1986贵州48优金樽奖；2011贵州十大名酒", "status": "在产", "trust": "已查证"},
  {"id": "gz-28", "name": "平坝窖酒", "en": "Pingba Jiao", "company": "贵州平坝酒业有限公司", "origin": "安顺市平坝区", "zone": "黔中产区", "aromaLabel": "兼香型（酱头浓尾）", "aroma": "other", "abv": 54, "abvAll": [54, 52], "craft": "浓酱兼香型工艺，大小曲并用、固态发酵", "nose": "酱香浓郁、入口幽雅、带明显药香", "palate": "酒体醇厚、绵甜", "products": "平坝窖酒（经典/年份）", "honors": "1963贵州老八大名酒；1986贵州48优金樽奖", "status": "在产", "trust": "已查证"},
  {"id": "gz-29", "name": "匀酒", "en": "Yunjiu", "company": "贵州匀酒（集团）／都匀酒厂", "origin": "黔南州都匀市", "zone": "黔南产区", "aromaLabel": "兼香型（酱头浓尾）", "aroma": "other", "abv": 52, "abvAll": [53, 52], "craft": "兼香型工艺，酱头浓尾；近年新增酱香型产品线（蓝花/红花）", "nose": "酱香打头、浓香收尾，香气协调", "palate": "醇厚带甜、酒体丰满", "products": "匀酒蓝花瓷、红花瓷", "honors": "1963贵州老八大名酒（真正的老八大之一）；1986贵州48优金樽奖", "status": "在产（万吨扩建列入贵州十四五规划）", "trust": "已查证"},
  {"id": "gz-30", "name": "湄窖", "en": "Meijiao", "company": "贵州湄窖酒业有限公司", "origin": "遵义市湄潭县", "zone": "黔北浓香带", "aromaLabel": "浓香型／酱香型", "aroma": "sauce", "abv": 52, "abvAll": [53, 52], "craft": "原以浓香泥窖固态发酵为主，现浓香＋酱香双线发展，酱香占两万吨年产能一半以上", "nose": "窖香浓郁、绵甜清雅（黔派浓香）", "palate": "绵甜爽净、香味协调", "products": "湄窖（经典/年份）、湄窖酱酒", "honors": "1986贵州48优金樽奖（湄窖酒、低度湄窖酒）", "status": "在产", "trust": "已查证"},
  {"id": "gz-31", "name": "贵州醇", "en": "Guizhou Chun", "company": "贵州醇酒业有限公司（现由江苏综艺集团控股）", "origin": "黔西南州兴义市", "zone": "黔西南产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 35, "abvAll": [53, 52, 35], "craft": "以低度浓香酒工艺闻名（首创35度低度白酒），近年增加酱香型产品", "nose": "窖香清雅、果香明显", "palate": "绵甜柔和、低度而不寡淡", "products": "贵州醇（经典35度）、贵州醇真年份", "honors": "1986贵州48优银樽奖；2011贵州十大名酒", "status": "在产", "trust": "已查证"},
  {"id": "gz-32", "name": "青酒", "en": "Qingjiu", "company": "贵州青酒集团有限责任公司", "origin": "黔东南州镇远县青溪镇", "zone": "黔东南产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52, 42], "craft": "浓香型固态发酵，近年增加酱香型产品线", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "青酒（喝杯青酒交个朋友系列）", "honors": "1986贵州48优铜樽奖（青溪大曲）；2011贵州十大名酒", "status": "在产", "trust": "已查证"},
  {"id": "gz-33", "name": "安酒", "en": "Anjiu", "company": "贵州安酒集团（现以赤水河酱酒基地为主）", "origin": "原安顺市，现产区移至赤水河流域", "zone": "黔中→赤水河", "aromaLabel": "浓香型→酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "历史上以浓香大曲为主；现专注大曲坤沙酱香，赤水河沿线布局，酱香基酒储备逾万吨", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "安酒国藏、安酒1951", "honors": "1963贵州老八大名酒；1986贵州48优金樽奖", "status": "在产（品牌复兴中）", "trust": "已查证"},
  {"id": "gz-34", "name": "岩博人民小酒", "en": "Yanbo Renmin Xiaojiu", "company": "贵州岩博酒业有限公司", "origin": "六盘水市盘州市淤泥乡岩博村", "zone": "黔西产区", "aromaLabel": "清酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 42], "craft": "传统小锅酿造工艺，纯粮固态发酵，清香与酱香融合，自成清酱香型", "nose": "清酱协调、香气幽雅", "palate": "醇厚丰满、细腻柔顺", "products": "人民小酒、藏龙液、小锅酒", "honors": "贵州清酱香型代表；2017年后全国知名", "status": "在产", "trust": "已查证"},
  {"id": "gz-35", "name": "贵酒（贵州贵酒集团）", "en": "Guijiu", "company": "贵州贵酒集团有限公司", "origin": "贵阳市（另有仁怀产区基地）", "zone": "黔中＋赤水河", "aromaLabel": "酱香型／浓香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 52], "craft": "酱香坤沙与浓香并行", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "贵酒·天蕴、贵酒·君道", "honors": "贵州老八大名酒品牌源流（贵阳大曲）", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-36", "name": "黔春酒", "en": "Qianchun", "company": "贵阳市酒厂／贵州黔春酒业", "origin": "贵阳市", "zone": "黔中产区", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [54, 53], "craft": "酱香型固态发酵", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "黔春酒、黔春特醇", "honors": "1986贵州48优金樽奖（黔春酒）、银樽奖（黔春特醇）", "status": "小规模在产", "trust": "史料/评选记载"},
  {"id": "gz-37", "name": "赖永初酒", "en": "Lai Yongchu", "company": "贵州赖永初酒业有限公司", "origin": "贵阳市／仁怀茅台镇", "zone": "黔中＋赤水河", "aromaLabel": "酱香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "酱香坤沙固态发酵", "nose": "酱香突出、焦香与糊香明显，优雅细腻", "palate": "醇厚丰满、酸度高、入口绵柔不辣喉", "products": "赖永初酒（年份系列）", "honors": "茅台恒兴烧房家族品牌", "status": "在产", "trust": "香型通则推定"},
  {"id": "gz-38", "name": "毕节大曲", "en": "Bijie Daqu", "company": "毕节市酒厂／贵州毕节大曲酒业", "origin": "毕节市七星关区", "zone": "黔西北产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型泥窖固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "毕节大曲", "honors": "1986贵州48优银樽奖", "status": "在产（区域性）", "trust": "史料/评选记载"},
  {"id": "gz-39", "name": "九龙液", "en": "Jiulongye", "company": "六枝特区酒厂／贵州九龙液酒业", "origin": "六盘水市六枝特区", "zone": "黔西产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "九龙液", "honors": "1986贵州48优银樽奖（黔龙牌九龙液）", "status": "区域性在产", "trust": "史料/评选记载"},
  {"id": "gz-40", "name": "赤水老窖", "en": "Chishui Laojiao", "company": "赤水市酒厂／贵州赤水老窖酒业", "origin": "遵义市赤水市", "zone": "赤水河下游特色产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [53, 52], "craft": "浓香型固态发酵，近年亦产酱香", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "赤水老窖", "honors": "1986贵州48优银樽奖（赤贵牌赤水老窖酒）", "status": "区域性在产", "trust": "史料/评选记载"},
  {"id": "gz-41", "name": "朱昌酒（朱昌窖酒）", "en": "Zhuchang", "company": "贵阳市朱昌酒厂", "origin": "贵阳市观山湖区朱昌镇", "zone": "黔中产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香窖酒固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "朱昌窖酒", "honors": "1986贵州48优银樽奖", "status": "区域性", "trust": "史料/评选记载"},
  {"id": "gz-42", "name": "阳关大曲", "en": "Yangguan Daqu", "company": "贵阳市阳关酒厂", "origin": "贵阳市", "zone": "黔中产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "阳关大曲", "honors": "1986贵州48优铜樽奖", "status": "区域性", "trust": "史料/评选记载"},
  {"id": "gz-43", "name": "碧春酒", "en": "Bichun", "company": "贵州碧春酒业", "origin": "贵阳市", "zone": "黔中产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "碧春酒", "honors": "贵州地方老牌（维基百科贵州白酒条目收录）", "status": "区域性；详细资料待查", "trust": "史料/评选记载"},
  {"id": "gz-44", "name": "贵州熏酒", "en": "Guizhou Xunjiu", "company": "贵州地方传统工艺（多家小厂）", "origin": "贵州省（黔北一带）", "zone": "－", "aromaLabel": "清香型（特殊熏制工艺）", "aroma": "light", "abv": 55, "abvAll": [55], "craft": "传统烟熏／熏蒸工艺制得，带特殊熏香", "nose": "带明显熏香、粮香", "palate": "口感浓烈直接", "products": "地方熏酒", "honors": "维基百科贵州白酒条目收录", "status": "民间／小规模生产；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-45", "name": "金壶春酒", "en": "Jinhuchun", "company": "平坝县酒厂", "origin": "安顺市平坝区", "zone": "黔中产区", "aromaLabel": "兼香型（酱头浓尾）", "aroma": "other", "abv": 54, "abvAll": [54], "craft": "与平坝窖酒同厂系工艺，兼香型", "nose": "酱香打头、浓香收尾，药香隐现", "palate": "醇厚带甜、酒体丰满", "products": "金壶春", "honors": "1986贵州48优银樽奖", "status": "已少见；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-46", "name": "颐年春酒", "en": "Yiniangchun", "company": "德江县酒厂", "origin": "铜仁市德江县", "zone": "黔东北产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "颐年春", "honors": "1986贵州48优银樽奖", "status": "已少见；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-47", "name": "黔北老窖", "en": "Qianbei Laojiao", "company": "遵义市黔北窖酒厂", "origin": "遵义市", "zone": "黔北浓香带", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型泥窖固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "黔北老窖", "honors": "1986贵州48优银樽奖", "status": "区域性；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-48", "name": "娄山春酒", "en": "Loushanchun", "company": "遵义市酿酒厂", "origin": "遵义市", "zone": "黔北浓香带", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "娄山春", "honors": "1986贵州48优银樽奖", "status": "区域性；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-49", "name": "福泉酒", "en": "Fuquan", "company": "福泉县酒厂", "origin": "黔南州福泉市", "zone": "黔南产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "福泉酒", "honors": "1986贵州48优银樽奖", "status": "区域性；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-50", "name": "乌江酒", "en": "Wujiang", "company": "思南县酒厂", "origin": "铜仁市思南县", "zone": "黔东北产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "乌江酒", "honors": "1986贵州48优铜樽奖", "status": "区域性；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-51", "name": "息烽窖酒", "en": "Xifeng Jiaojiu", "company": "息烽县酒厂", "origin": "贵阳市息烽县", "zone": "黔中产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香窖酒固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "息烽窖酒", "honors": "1986贵州48优铜樽奖", "status": "区域性；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-52", "name": "涟江大曲", "en": "Lianjiang Daqu", "company": "惠水县酒厂", "origin": "黔南州惠水县", "zone": "黔南产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "涟江大曲", "honors": "1986贵州48优铜樽奖", "status": "区域性；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-53", "name": "大关酒", "en": "Daguan", "company": "石阡县大关酒厂", "origin": "铜仁市石阡县", "zone": "黔东北产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "大关酒", "honors": "1986贵州48优铜樽奖", "status": "区域性；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-54", "name": "南盘江窖酒", "en": "Nanpanjiang", "company": "兴义县酒厂（贵州醇前身厂系）", "origin": "黔西南州兴义市", "zone": "黔西南产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "南盘江窖酒", "honors": "1986贵州48优银樽奖", "status": "已整合入贵州醇体系", "trust": "史料/评选记载"},
  {"id": "gz-55", "name": "芙蓉江窖酒", "en": "Furongjiang", "company": "道真县芙蓉江酒厂", "origin": "遵义市道真县", "zone": "黔北产区", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "芙蓉江窖酒", "honors": "1986贵州48优银樽奖", "status": "区域性；资料待查", "trust": "史料/评选记载"},
  {"id": "gz-56", "name": "泉酒", "en": "Quanjiu", "company": "贵州泉酒厂（历史企业）", "origin": "贵州省（原评选记载）", "zone": "－", "aromaLabel": "浓香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "浓香型固态发酵", "nose": "窖香浓郁、以己酸乙酯为主体香", "palate": "绵甜爽净、香味协调", "products": "泉酒", "honors": "1963贵州老八大名酒（第二届被习水大曲、贵阳大曲取代）", "status": "已停产／资料待查", "trust": "史料/评选记载"}
]

export const BAIJIU_BY_ID = Object.fromEntries(BAIJIU.map((b) => [b.id, b]))

/** 依产区带分组，供下拉菜单使用 */
export function groupedByZone(): { zone: string; items: Baijiu[] }[] {
  const m = new Map<string, Baijiu[]>()
  for (const b of BAIJIU) {
    const z = b.zone ?? '其他产区'
    if (!m.has(z)) m.set(z, [])
    m.get(z)!.push(b)
  }
  return [...m.entries()].map(([zone, items]) => ({ zone, items }))
}
