/**
 * 貴州白酒品項庫（56 支）。
 * 來源：團隊《貴州白酒完整資料庫》，欄位含香型、典型酒精度、工藝與風味描述。
 * 用途：讓外貿專員直接選「你家要出的是哪一支」，而不是憑空填參數——
 * 選完之後香型、度數、風味描述會一起帶進落地價測算與賣點彈藥。
 */
import type { AromaId } from './aroma'

export type Baijiu = {
  id: string
  name: string
  en: string | null
  company: string | null
  origin: string | null
  zone: string | null
  aromaLabel: string | null
  aroma: AromaId | 'other'
  /** 典型酒精度 */
  abv: number
  /** 該品牌已有的度數版本（含低度版） */
  abvAll: number[]
  craft: string | null
  nose: string | null
  palate: string | null
  products: string | null
  honors: string | null
  status: string | null
  trust: string | null
}

export const BAIJIU: Baijiu[] = [
  {"id": "gz-01", "name": "茅台酒", "en": "Moutai / Maotai", "company": "貴州茅台酒股份有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區（茅台酒15.03km²核心區）", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 43, 38], "craft": "坤沙固態發酵：兩次投料、九次蒸煮、八次發酵、七次取酒（12987），生產週期一年，基酒貯存三年以上，勾兌後再貯存一年，全程近五年", "nose": "醬香突出、香氣優雅細膩、焦香與花果香層次分明", "palate": "醇厚豐滿、酸度高、入口柔綿不燒喉", "products": "飛天茅台、五星茅台、茅台年份酒（15/30/50/80年）、珍品茅台", "honors": "1963貴州老八大名酒；1986貴州48優金樽獎；歷屆中國名酒；國家地理標誌產品", "status": "在產（國內白酒龍頭）", "trust": "已查證"},
  {"id": "gz-02", "name": "茅台王子酒", "en": "Maotai Wangzi", "company": "貴州茅台酒股份有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "與茅台酒同源之坤沙12987工藝，基酒等級與貯存年限低於飛天茅台", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "茅台王子酒（金王子/珍品/生肖）", "honors": "2011貴州十大名酒", "status": "在產（茅台系列酒主力）", "trust": "已查證"},
  {"id": "gz-03", "name": "茅台迎賓酒", "en": "Maotai Yingbin", "company": "貴州茅台酒股份有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙／碎沙結合之醬香工藝", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇和柔順、酒體較輕盈", "products": "迎賓酒（紫/金/王）", "honors": "茅台系列酒", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-04", "name": "貴州大曲", "en": "Guizhou Daqu", "company": "貴州茅台酒股份有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 50], "craft": "醬香固態發酵（現行產品為醬香型；歷史上的貴陽大曲/貴州大曲曾為濃香型，二者需區分）", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "貴州大曲（15年/30年、金醬/柔雅）", "honors": "1979貴州新八大名酒（貴陽大曲）", "status": "在產", "trust": "已查證"},
  {"id": "gz-05", "name": "漢醬酒", "en": "Hanjiang", "company": "貴州茅台酒股份有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 51, "abvAll": [51], "craft": "醬香12987工藝，以51度中度醬香為特色", "nose": "醬香突出、略帶蜜甜與焦香", "palate": "酒體較柔和、入口綿順", "products": "漢醬（匠心營造/135）", "honors": "茅台醬香系列酒", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-06", "name": "仁酒", "en": "Renjiu", "company": "貴州茅台酒股份有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "醬香12987工藝", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "茅台仁酒", "honors": "茅台醬香系列酒", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-07", "name": "賴茅", "en": "Laimao", "company": "貴州茅台酒廠（集團）賴茅酒業有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "醬香坤沙固態發酵", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "賴茅傳承藍/端曲/珍藏", "honors": "茅台三大燒房之一（恒興燒房）源流", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-08", "name": "華茅", "en": "Huamao", "company": "貴州茅台酒廠（集團）華茅酒業有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "醬香坤沙固態發酵", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "華茅1862、華茅酒", "honors": "茅台三大燒房之一（成義燒房）源流", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-09", "name": "王茅", "en": "Wangmao", "company": "貴州茅台酒廠（集團）保健酒業／王茅品牌", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "醬香坤沙固態發酵", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "王茅酒、王茅使者", "honors": "茅台三大燒房之一（榮和燒房）源流", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-10", "name": "習酒", "en": "Xijiu", "company": "貴州習酒股份有限公司（原屬茅台集團，現獨立運營）", "origin": "遵義市習水縣習酒鎮", "zone": "赤水河中游（習水產區集聚區68.4km²）", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 52, 45], "craft": "赤水河谷傳統固態法：兩次投料、九次蒸煮、八次發酵、七次取酒，生產週期一年，長期陶壇貯存", "nose": "醬香突出、香氣細膩純正", "palate": "醇厚豐滿、綿柔協調", "products": "君品習酒、窖藏1988、金質/銀質習酒", "honors": "1986貴州48優金樽獎；2011貴州十大名酒", "status": "在產（貴州第二大酒企）", "trust": "已查證"},
  {"id": "gz-11", "name": "習水大曲", "en": "Xishui Daqu", "company": "貴州習酒股份有限公司", "origin": "遵義市習水縣", "zone": "赤水河中游", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52, 38], "craft": "濃香型固態續糟發酵、泥窖老窖", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "習水大曲（經典/老標）", "honors": "1979貴州新八大名酒；1986貴州48優金樽獎", "status": "在產（習酒濃香產品線）", "trust": "史料/評選記載"},
  {"id": "gz-12", "name": "珍酒", "en": "Zhenjiu", "company": "珍酒李渡集團／貴州珍酒釀酒有限公司", "origin": "遵義市匯川區（原遵義酒精廠址）", "zone": "遵義匯川特色產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "茅台工藝異地移植：坤沙12987、長期貯存勾調，被稱為「易地茅台」", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "珍十五、珍三十、珍酒真藏", "honors": "1986貴州48優銀樽獎；國家科技進步獎（易地茅台試驗）", "status": "在產（港股上市集團核心品牌）", "trust": "已查證"},
  {"id": "gz-13", "name": "國台酒", "en": "Guotai", "company": "貴州國台酒業集團（天士力控股）", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區（茅台鎮傳統優勢區）", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙12987，以智能釀造與數字化品控著稱，基酒貯存5年以上", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "國台國標酒、國台十五年、龍酒", "honors": "2011貴州十大名酒；被稱茅台鎮第二大釀酒企業", "status": "在產", "trust": "已查證"},
  {"id": "gz-14", "name": "釣魚台酒", "en": "Diaoyutai", "company": "貴州釣魚台國賓酒業有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "傳承古典醬香工藝、天然釀製，坤沙12987", "nose": "醬香幽雅、細膩協調", "palate": "醇和優雅、酒體綿柔", "products": "釣魚台國賓酒、珍品／年份系列", "honors": "國賓館用酒品牌授權", "status": "在產", "trust": "已查證"},
  {"id": "gz-15", "name": "金沙回沙酒", "en": "Jinsha Huisha", "company": "貴州金沙窖酒酒業有限公司", "origin": "畢節市金沙縣", "zone": "赤水河上游（金沙特色產區）", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "與茅台同源之回沙工藝：兩次投料、九次蒸煮、八次發酵、七次取酒", "nose": "醬香突出、伴焦香與花果香，優雅細膩", "palate": "醇厚協調、層次分明、口感均衡", "products": "金沙摘要、金沙回沙鑽石五星／年份、金沙六星", "honors": "1963貴州老八大名酒（金沙窖酒）；1986貴州48優銀樽獎；2011貴州十大名酒", "status": "在產", "trust": "已查證"},
  {"id": "gz-16", "name": "懷莊酒", "en": "Huaizhuang", "company": "貴州懷莊酒業（集團）有限責任公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙醬香12987固態發酵", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "懷莊之醉、懷莊1983", "honors": "茅台鎮早期民營酒企之一", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-17", "name": "夜郎古酒", "en": "Yelanggu", "company": "貴州夜郎古酒業股份有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙醬香12987", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "夜郎古酒（藏品/尊品）", "honors": "以夜郎文化為品牌核心", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-18", "name": "小糊塗仙", "en": "Xiaohutuxian", "company": "貴州小糊塗仙酒業（雲峰酒業）", "origin": "遵義市仁懷市茅台鎮（另有習水土城及四川合江基地）", "zone": "赤水河流域", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [53, 52], "craft": "傳統濃香固態發酵結合現代生物技術；醬香產品採赤水河醬香工藝", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "小糊塗仙普仙、小糊塗神、糊塗尊", "honors": "1990年代廣東市場現象級品牌", "status": "在產", "trust": "已查證"},
  {"id": "gz-19", "name": "百年糊塗", "en": "Bainian Hutu", "company": "貴州仁懷茅台鎮糊塗酒業有限公司（佛山吉利貿易運營）", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "百年糊塗精品、海藏珍品", "honors": "2011貴州十大名酒", "status": "在產", "trust": "已查證"},
  {"id": "gz-20", "name": "酒中酒霸", "en": "Jiuzhongjiuba", "company": "貴州酒中酒（集團）有限責任公司", "origin": "遵義市仁懷市", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 52], "craft": "集團同時具備醬香與濃香兩條產線；醬香採坤沙工藝", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "酒中酒霸、本強系列", "honors": "2011貴州十大名酒", "status": "在產", "trust": "已查證"},
  {"id": "gz-21", "name": "無憂酒", "en": "Wuyou", "company": "貴州無憂酒業有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙醬香12987", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "無憂酒系列", "honors": "茅台鎮區域品牌", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-22", "name": "金醬酒", "en": "Jinjiang", "company": "貴州金醬酒業有限公司", "origin": "遵義市仁懷市茅台鎮", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙醬香12987", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "金醬酒（年份/傳承）", "honors": "茅台鎮區域品牌", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-23", "name": "國威酒", "en": "Guowei", "company": "貴州國威酒業（集團）有限公司", "origin": "遵義市仁懷市", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "坤沙醬香固態發酵", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "國威酒系列", "honors": "仁懷本地老牌酒企", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-24", "name": "懷酒", "en": "Huaijiu", "company": "仁懷懷酒廠（現屬茅台集團體系）", "origin": "遵義市仁懷市", "zone": "赤水河核心產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "醬香固態發酵", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "懷酒", "honors": "1986貴州48優金樽獎", "status": "在產（品牌經多次易手）", "trust": "史料/評選記載"},
  {"id": "gz-25", "name": "播窖1935", "en": "Bojiao 1935", "company": "貴州播窖酒業", "origin": "遵義市播州區", "zone": "遵義播州特色產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "醬香固態發酵", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "播窖1935", "honors": "區域新品牌", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-26", "name": "董酒", "en": "Dongjiu", "company": "貴州董酒股份有限公司", "origin": "遵義市匯川區董公寺鎮", "zone": "遵義董公寺（獨立產區）", "aromaLabel": "董香型（藥香型）", "aroma": "herbal", "abv": 54, "abvAll": [59, 54, 38], "craft": "串香＋雙醅法：大窖（泥窖）產香醅、小窖（土窖）產酒醅，兩醅串蒸；「百草入曲、兩小兩大、雙醅串蒸」", "nose": "藥香（百草香）舒適優雅，酯香、醇香、藥香協調", "palate": "醇和濃郁、飲後甘爽、微帶酸澀而回甜", "products": "國密董酒、佰草香、密藏、紅標／白標董酒", "honors": "中國老八大名酒；1963貴州老八大名酒；1986貴州48優金樽獎；2011貴州十大名酒；工藝列入國家", "status": "在產", "trust": "已查證"},
  {"id": "gz-27", "name": "鴨溪窖酒", "en": "Yaxi Jiao", "company": "貴州鴨溪窖酒有限公司", "origin": "遵義市播州區鴨溪鎮", "zone": "黔北濃香帶", "aromaLabel": "濃香型（帶兼香特徵：入口濃香、回味醬香）", "aroma": "sauce", "abv": 53, "abvAll": [55], "craft": "泥窖固態續糟發酵，濃香工藝但成品帶醬香尾韻，稱「黔派濃香」", "nose": "芳香濃郁、入口濃香而回味帶醬", "palate": "醇甜爽口、甜而不暴", "products": "鴨溪窖酒（經典/珍品）", "honors": "1963貴州老八大名酒；1986貴州48優金樽獎；2011貴州十大名酒", "status": "在產", "trust": "已查證"},
  {"id": "gz-28", "name": "平壩窖酒", "en": "Pingba Jiao", "company": "貴州平壩酒業有限公司", "origin": "安順市平壩區", "zone": "黔中產區", "aromaLabel": "兼香型（醬頭濃尾）", "aroma": "other", "abv": 54, "abvAll": [54, 52], "craft": "濃醬兼香型工藝，大小曲並用、固態發酵", "nose": "醬香濃郁、入口幽雅、帶明顯藥香", "palate": "酒體醇厚、綿甜", "products": "平壩窖酒（經典/年份）", "honors": "1963貴州老八大名酒；1986貴州48優金樽獎", "status": "在產", "trust": "已查證"},
  {"id": "gz-29", "name": "匀酒", "en": "Yunjiu", "company": "貴州匀酒（集團）／都勻酒廠", "origin": "黔南州都勻市", "zone": "黔南產區", "aromaLabel": "兼香型（醬頭濃尾）", "aroma": "other", "abv": 52, "abvAll": [53, 52], "craft": "兼香型工藝，醬頭濃尾；近年新增醬香型產品線（藍花/紅花）", "nose": "醬香打頭、濃香收尾，香氣協調", "palate": "醇厚帶甜、酒體豐滿", "products": "匀酒藍花瓷、紅花瓷", "honors": "1963貴州老八大名酒（真正的老八大之一）；1986貴州48優金樽獎", "status": "在產（萬噸擴建列入貴州十四五規劃）", "trust": "已查證"},
  {"id": "gz-30", "name": "湄窖", "en": "Meijiao", "company": "貴州湄窖酒業有限公司", "origin": "遵義市湄潭縣", "zone": "黔北濃香帶", "aromaLabel": "濃香型／醬香型", "aroma": "sauce", "abv": 52, "abvAll": [53, 52], "craft": "原以濃香泥窖固態發酵為主，現濃香＋醬香雙線發展，醬香佔兩萬噸年產能一半以上", "nose": "窖香濃郁、綿甜清雅（黔派濃香）", "palate": "綿甜爽淨、香味協調", "products": "湄窖（經典/年份）、湄窖醬酒", "honors": "1986貴州48優金樽獎（湄窖酒、低度湄窖酒）", "status": "在產", "trust": "已查證"},
  {"id": "gz-31", "name": "貴州醇", "en": "Guizhou Chun", "company": "貴州醇酒業有限公司（現由江蘇綜藝集團控股）", "origin": "黔西南州興義市", "zone": "黔西南產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 35, "abvAll": [53, 52, 35], "craft": "以低度濃香酒工藝聞名（首創35度低度白酒），近年增加醬香型產品", "nose": "窖香清雅、果香明顯", "palate": "綿甜柔和、低度而不寡淡", "products": "貴州醇（經典35度）、貴州醇真年份", "honors": "1986貴州48優銀樽獎；2011貴州十大名酒", "status": "在產", "trust": "已查證"},
  {"id": "gz-32", "name": "青酒", "en": "Qingjiu", "company": "貴州青酒集團有限責任公司", "origin": "黔東南州鎮遠縣青溪鎮", "zone": "黔東南產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52, 42], "craft": "濃香型固態發酵，近年增加醬香型產品線", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "青酒（喝杯青酒交個朋友系列）", "honors": "1986貴州48優銅樽獎（青溪大曲）；2011貴州十大名酒", "status": "在產", "trust": "已查證"},
  {"id": "gz-33", "name": "安酒", "en": "Anjiu", "company": "貴州安酒集團（現以赤水河醬酒基地為主）", "origin": "原安順市，現產區移至赤水河流域", "zone": "黔中→赤水河", "aromaLabel": "濃香型→醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "歷史上以濃香大曲為主；現專注大曲坤沙醬香，赤水河沿線佈局，醬香基酒儲備逾萬噸", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "安酒國藏、安酒1951", "honors": "1963貴州老八大名酒；1986貴州48優金樽獎", "status": "在產（品牌復興中）", "trust": "已查證"},
  {"id": "gz-34", "name": "岩博人民小酒", "en": "Yanbo Renmin Xiaojiu", "company": "貴州岩博酒業有限公司", "origin": "六盤水市盤州市淤泥鄉岩博村", "zone": "黔西產區", "aromaLabel": "清醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 42], "craft": "傳統小鍋釀造工藝，純糧固態發酵，清香與醬香融合，自成清醬香型", "nose": "清醬協調、香氣幽雅", "palate": "醇厚豐滿、細膩柔順", "products": "人民小酒、藏龍液、小鍋酒", "honors": "貴州清醬香型代表；2017年後全國知名", "status": "在產", "trust": "已查證"},
  {"id": "gz-35", "name": "貴酒（貴州貴酒集團）", "en": "Guijiu", "company": "貴州貴酒集團有限公司", "origin": "貴陽市（另有仁懷產區基地）", "zone": "黔中＋赤水河", "aromaLabel": "醬香型／濃香型", "aroma": "sauce", "abv": 53, "abvAll": [53, 52], "craft": "醬香坤沙與濃香並行", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "貴酒·天蘊、貴酒·君道", "honors": "貴州老八大名酒品牌源流（貴陽大曲）", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-36", "name": "黔春酒", "en": "Qianchun", "company": "貴陽市酒廠／貴州黔春酒業", "origin": "貴陽市", "zone": "黔中產區", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [54, 53], "craft": "醬香型固態發酵", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "黔春酒、黔春特醇", "honors": "1986貴州48優金樽獎（黔春酒）、銀樽獎（黔春特醇）", "status": "小規模在產", "trust": "史料/評選記載"},
  {"id": "gz-37", "name": "賴永初酒", "en": "Lai Yongchu", "company": "貴州賴永初酒業有限公司", "origin": "貴陽市／仁懷茅台鎮", "zone": "黔中＋赤水河", "aromaLabel": "醬香型", "aroma": "sauce", "abv": 53, "abvAll": [53], "craft": "醬香坤沙固態發酵", "nose": "醬香突出、焦香與糊香明顯，優雅細膩", "palate": "醇厚豐滿、酸度高、入口綿柔不辣喉", "products": "賴永初酒（年份系列）", "honors": "茅台恒興燒房家族品牌", "status": "在產", "trust": "香型通則推定"},
  {"id": "gz-38", "name": "畢節大曲", "en": "Bijie Daqu", "company": "畢節市酒廠／貴州畢節大曲酒業", "origin": "畢節市七星關區", "zone": "黔西北產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型泥窖固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "畢節大曲", "honors": "1986貴州48優銀樽獎", "status": "在產（區域性）", "trust": "史料/評選記載"},
  {"id": "gz-39", "name": "九龍液", "en": "Jiulongye", "company": "六枝特區酒廠／貴州九龍液酒業", "origin": "六盤水市六枝特區", "zone": "黔西產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "九龍液", "honors": "1986貴州48優銀樽獎（黔龍牌九龍液）", "status": "區域性在產", "trust": "史料/評選記載"},
  {"id": "gz-40", "name": "赤水老窖", "en": "Chishui Laojiao", "company": "赤水市酒廠／貴州赤水老窖酒業", "origin": "遵義市赤水市", "zone": "赤水河下游特色產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [53, 52], "craft": "濃香型固態發酵，近年亦產醬香", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "赤水老窖", "honors": "1986貴州48優銀樽獎（赤貴牌赤水老窖酒）", "status": "區域性在產", "trust": "史料/評選記載"},
  {"id": "gz-41", "name": "朱昌酒（朱昌窖酒）", "en": "Zhuchang", "company": "貴陽市朱昌酒廠", "origin": "貴陽市觀山湖區朱昌鎮", "zone": "黔中產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香窖酒固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "朱昌窖酒", "honors": "1986貴州48優銀樽獎", "status": "區域性", "trust": "史料/評選記載"},
  {"id": "gz-42", "name": "陽關大曲", "en": "Yangguan Daqu", "company": "貴陽市陽關酒廠", "origin": "貴陽市", "zone": "黔中產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "陽關大曲", "honors": "1986貴州48優銅樽獎", "status": "區域性", "trust": "史料/評選記載"},
  {"id": "gz-43", "name": "碧春酒", "en": "Bichun", "company": "貴州碧春酒業", "origin": "貴陽市", "zone": "黔中產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "碧春酒", "honors": "貴州地方老牌（維基百科貴州白酒條目收錄）", "status": "區域性；詳細資料待查", "trust": "史料/評選記載"},
  {"id": "gz-44", "name": "貴州熏酒", "en": "Guizhou Xunjiu", "company": "貴州地方傳統工藝（多家小廠）", "origin": "貴州省（黔北一帶）", "zone": "－", "aromaLabel": "清香型（特殊熏製工藝）", "aroma": "light", "abv": 55, "abvAll": [55], "craft": "傳統煙熏／熏蒸工藝製得，帶特殊熏香", "nose": "帶明顯熏香、糧香", "palate": "口感濃烈直接", "products": "地方熏酒", "honors": "維基百科貴州白酒條目收錄", "status": "民間／小規模生產；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-45", "name": "金壺春酒", "en": "Jinhuchun", "company": "平壩縣酒廠", "origin": "安順市平壩區", "zone": "黔中產區", "aromaLabel": "兼香型（醬頭濃尾）", "aroma": "other", "abv": 54, "abvAll": [54], "craft": "與平壩窖酒同廠系工藝，兼香型", "nose": "醬香打頭、濃香收尾，藥香隱現", "palate": "醇厚帶甜、酒體豐滿", "products": "金壺春", "honors": "1986貴州48優銀樽獎", "status": "已少見；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-46", "name": "頤年春酒", "en": "Yiniangchun", "company": "德江縣酒廠", "origin": "銅仁市德江縣", "zone": "黔東北產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "頤年春", "honors": "1986貴州48優銀樽獎", "status": "已少見；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-47", "name": "黔北老窖", "en": "Qianbei Laojiao", "company": "遵義市黔北窖酒廠", "origin": "遵義市", "zone": "黔北濃香帶", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型泥窖固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "黔北老窖", "honors": "1986貴州48優銀樽獎", "status": "區域性；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-48", "name": "婁山春酒", "en": "Loushanchun", "company": "遵義市釀酒廠", "origin": "遵義市", "zone": "黔北濃香帶", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "婁山春", "honors": "1986貴州48優銀樽獎", "status": "區域性；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-49", "name": "福泉酒", "en": "Fuquan", "company": "福泉縣酒廠", "origin": "黔南州福泉市", "zone": "黔南產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "福泉酒", "honors": "1986貴州48優銀樽獎", "status": "區域性；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-50", "name": "烏江酒", "en": "Wujiang", "company": "思南縣酒廠", "origin": "銅仁市思南縣", "zone": "黔東北產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "烏江酒", "honors": "1986貴州48優銅樽獎", "status": "區域性；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-51", "name": "息烽窖酒", "en": "Xifeng Jiaojiu", "company": "息烽縣酒廠", "origin": "貴陽市息烽縣", "zone": "黔中產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香窖酒固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "息烽窖酒", "honors": "1986貴州48優銅樽獎", "status": "區域性；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-52", "name": "涟江大曲", "en": "Lianjiang Daqu", "company": "惠水縣酒廠", "origin": "黔南州惠水縣", "zone": "黔南產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "涟江大曲", "honors": "1986貴州48優銅樽獎", "status": "區域性；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-53", "name": "大關酒", "en": "Daguan", "company": "石阡縣大關酒廠", "origin": "銅仁市石阡縣", "zone": "黔東北產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "大關酒", "honors": "1986貴州48優銅樽獎", "status": "區域性；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-54", "name": "南盤江窖酒", "en": "Nanpanjiang", "company": "興義縣酒廠（貴州醇前身廠系）", "origin": "黔西南州興義市", "zone": "黔西南產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "南盤江窖酒", "honors": "1986貴州48優銀樽獎", "status": "已整合入貴州醇體系", "trust": "史料/評選記載"},
  {"id": "gz-55", "name": "芙蓉江窖酒", "en": "Furongjiang", "company": "道真縣芙蓉江酒廠", "origin": "遵義市道真縣", "zone": "黔北產區", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "芙蓉江窖酒", "honors": "1986貴州48優銀樽獎", "status": "區域性；資料待查", "trust": "史料/評選記載"},
  {"id": "gz-56", "name": "泉酒", "en": "Quanjiu", "company": "貴州泉酒廠（歷史企業）", "origin": "貴州省（原評選記載）", "zone": "－", "aromaLabel": "濃香型", "aroma": "strong", "abv": 52, "abvAll": [52], "craft": "濃香型固態發酵", "nose": "窖香濃郁、以己酸乙酯為主體香", "palate": "綿甜爽淨、香味協調", "products": "泉酒", "honors": "1963貴州老八大名酒（第二屆被習水大曲、貴陽大曲取代）", "status": "已停產／資料待查", "trust": "史料/評選記載"}
]

export const BAIJIU_BY_ID = Object.fromEntries(BAIJIU.map((b) => [b.id, b]))

/** 依產區帶分組，供下拉選單使用 */
export function groupedByZone(): { zone: string; items: Baijiu[] }[] {
  const m = new Map<string, Baijiu[]>()
  for (const b of BAIJIU) {
    const z = b.zone ?? '其他產區'
    if (!m.has(z)) m.set(z, [])
    m.get(z)!.push(b)
  }
  return [...m.entries()].map(([zone, items]) => ({ zone, items }))
}
